PERF-4691 Add index consistency checks to perf canary workloads
mongodb/genny pull request #1013
Opened 2023-09-12 01:59 UTC by moustafamaher

Thanks for submitting a PR to the Genny repo. Please include the following fields (if relevant) prior to submitting your PR.

**Jira Ticket:** < [SERVER-79695](https://jira.mongodb.org/browse/SERVER-79695), [PERF-4691](https://jira.mongodb.org/browse/PERF-4691) >

**Whats Changed:**  
Add index consistency checks to perf canary workloads

**Patch testing results:**  
[Link](https://spruce.mongodb.com/version/64ff42ebd1fe07cd9a85e2b2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Related PRs:**

2023-09-12 09:10 UTC, SimonEismann requested changes
LGTM, one of the actors might have the wrong phase number though.

2023-09-12 09:10 UTC, SimonEismann commented on src/workloads/replication/dbcheck/dbcheck_40GB.yml
> +        Duration: 15 minutes
I guess if the test takes ~4 hours, it's not that impactful.

2023-09-13 03:26 UTC, moustafamaher commented on src/cast_core/src/DbCheckActor.cpp
> +            }
Yes I have added this actor last ticket, but I couldn't add them to the test, as they require a feature flag to be set and I am not sure where can I make sure its set.

2023-09-13 03:27 UTC, moustafamaher commented on src/workloads/replication/dbcheck/dbcheck_40GB.yml
>        Active: [2]
Wow Nice catch!

2023-09-13 03:28 UTC, moustafamaher commented on src/workloads/replication/dbcheck/dbcheck_40GB.yml
> +        Duration: 15 minutes
I made it 15 min, because all other stages (dbcheck) For that load always takes around 15 min.

2023-09-14 09:52 UTC, SimonEismann approved these changes
LGTM!

2023-09-14 16:42 UTC, merged