PERF-4347 Combine QE workloads using conditional sharding
mongodb/genny pull request #1044
Opened 2023-10-13 16:41 UTC by alicedoherty

**Jira Ticket:** [PERF-4347](https://jira.mongodb.org/browse/PERF-4347)

**Whats Changed:**  
- The non-sharded and sharded versions of the [YCSB-like queryable encryption](https://github.com/mongodb/genny/tree/master/src/workloads/encrypted) workloads have been combined into one file using the [OnlyRunInInstance functionality](https://github.com/mongodb/genny/blob/master/src/cast_core/src/RunCommand.cpp#L216).
- (Note: I've also updated [ExponentialCompact.yml](https://github.com/mongodb/genny/blob/master/src/workloads/encrypted/ExponentialCompact.yml) even though it doesn't have a sharded version because it referenced the `ShardCollectionPhase` param that I cleaned up to use `OnlyRunInInstance: sharded` instead).

**Patch Testing Results:**  
- [Updated QE workloads running on Linux-1-Node ReplSet FLE 2022-11](https://spruce.mongodb.com/version/65295b5f3627e0465ba94e59/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and [Perf Analyser results](https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=e41e6b67-768b-4fd4-8db9-e46fd2616e17&percent_filter=0%7C%7C100&z_filter=0%7C%7C10)
- [Updated QE workloads running on Linux Shard Lite FLE 2022-11](https://spruce.mongodb.com/version/6526b8c81e2d1765dc75ab91/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (can't use Perf Analyser to look at the sharded tests as the task name has changed - but manual inspection showed no performance changes).

**Related PRs:**   
- TODO put up PR for [SERVER-82178](https://jira.mongodb.org/browse/SERVER-82178)

2023-10-16 11:31 UTC, roganamy commented
See comment on https://github.com/10gen/mongo/pull/16239/files
You'll need another reviewer for both PRs aswell

2023-10-16 13:22 UTC, roganamy commented
Do we expect to see a performance difference with these changes?

2023-10-16 15:21 UTC, erwee requested changes
Glad to see our workload files reduced by a half. Thanks for doing this work!

2023-10-16 15:21 UTC, erwee commented on src/phases/encrypted/ContinuousWritesWithExponentialCompactTemplate.yml
> +            key: {field9: hashed}
```suggestion
            key: {field1: hashed}
```

2023-10-16 16:01 UTC, alicedoherty commented on src/phases/encrypted/ContinuousWritesWithExponentialCompactTemplate.yml
> +            key: {field9: hashed}
Copy and paste error sorry! Nice catch.

2023-10-16 16:14 UTC, erwee approved these changes

2023-10-18 10:46 UTC, roganamy approved these changes

2023-10-20 10:22 UTC, alicedoherty commented
evergreen merge

2023-10-20 11:39 UTC, merged