DEVPROD-1625: Compile genny on Amazon Linux 2023 (al2023.0)
mongodb/genny pull request #1068
Opened 2023-11-23 09:34 UTC by lgfang

**Jira Ticket:** DEVPROD-1625

**Whats Changed:**

Compile genny on Amazon Linux 2023 (al2023.0).

Things worth noting:

-   `TOOLCHAIN_BUILD_ID` will be updated once [corresponding genny toolchain PR](https://github.com/10gen/vcpkg/pull/31) is merged and a new waterfall build of genny toolchain is done.

-   Why al2023.0 not al2023.2?
    
    Currently, the mongodb toolchain version used by evergreen does not work with al2023.2. The error is the following (on al2023.2, the available SO verison is libffi.so.8):
    
    ```text
    ImportError: libffi.so.6: cannot open shared object file: No such file or
    directory
    ```
    
    The latest mongodb toolchain has alrady been rebuilt on al2023.2 to fix this issue. Hence, when evergreen adopts the latest toolchain (an indication could be being unable to find libffi.so.8), update the `run_on` host to `amazon2023.2-...`.

-   Why we run `resmoke-test` on amazon2, why not do the same on al2023?
    -   Firstly, it is unnecessary because we do not run `resmoke-test` on every platform anyways.
    
    -   Secondly, `resmoke-test` works with mongodb 6.0 only (DEVPROD-2925) but we don't have mongodb6.0 for al2023.

**Patch testing results:**

None

**Related PRs:**

https://github.com/10gen/vcpkg/pull/31

2023-12-12 06:18 UTC, thessem requested changes
From what I can see https://github.com/mongodb/genny/pull/1083 is a superset of this PR, and I think the other one might be the one we'll go with. Let me know if I'm misreading this and I'll re-review this PR

2023-12-12 22:41 UTC, lgfang commented
> From what I can see #1083 is a superset of this PR, and I think the other one might be the one we'll go with. Let me know if I'm misreading this and I'll re-review this PR

I based PR #1083 on this PR so that new toolchain is tested on al2023 as well. Hence, PR #1083 appears to be a super set of this PR. But in terms of code changes, these two PRs do not depend on each other.

I'd prefer to merge in this PR first and then continue to work on/merge in the other one. 
- These two PRs focus on different things:
    - This PR is for enabling AL2023 and the impact to the existing tests is minimal. 
    - In comparison, the focus of PR #1083 is upgrading genny toolchain and the performance impact is unknown yet (I'm working on comparing performance before/after toolchain now).
- Merge in them separately allows us to revert changes separately should anything unexpected happen.

2024-01-08 05:45 UTC, thessem approved these changes

2024-01-08 06:50 UTC, lgfang commented
evergreen merge

2024-01-08 07:24 UTC, lgfang commented
evergreen merge

2024-01-08 09:06 UTC, merged