DEVPROD-5757 Require owners, descriptions, and keywords in all workload files.
mongodb/genny pull request #1171
Opened 2024-03-26 16:50 UTC by ahartschen

**Jira Ticket:** DEVPROD-5757

**Whats Changed:**  
We now require that all workload files have these required fields. We made some exceptions for older files that did not have keywords. Any future workloads will require all the fields. I also changed things up to disable the formatting check because this was disabled about 2 years ago and there were ~13k errors that need corrected. I opened DEVPROD-5682 to have this addressed.

**Patch testing results:**  
Running the CLI locally, no output since there are no errors:

```
(genny_venv) ➜  genny git:(DEVPROD-5757) ./run-genny lint-yaml --no-format
(genny_venv) ➜  genny git:(DEVPROD-5757) 
```

**Workload Submission form:**  
If applicable, only required if there is a new workload being added. Form can be found [here](https://docs.google.com/forms/d/1r0kOHvFUa7rJxVmX_wp9prxYU5K155yKyZ1y3d5yhZg/edit)

**Related PRs:**   
N/A

PLEASE READ AND REMOVE THE SECTION BELOW BEFORE SUBMITTING YOUR PR FOR REVIEW

1.  Once (1) you get approval from the STM or the Product Perf team for your change and (2) all your CI tests pass, you can initiate a merge by entering a comment on your PR with the text

    > evergreen merge

    This kicks your PR into the [evergreen commit queue][ecq]. Evergreen will automatically squash-merge your commit after checking that you have PR approval and that the CI tests all pass.

[ecq]: https://github.com/evergreen-ci/evergreen/wiki/Commit-Queue

2024-03-27 03:12 UTC, thessem approved these changes
From a perf infra point of view everything here looks good. I'd still wait for somebody from Product Perf on the test-config implications.

2024-03-27 10:46 UTC, MAhmadShah commented on src/lamplib/src/genny/tasks/yaml_linter.py
> +        if field not in workload:
NIT: Do you think it's also worth checking that the field actually has some text in it? There could be a loop hole here where users can just put the key in with an empty value.

2024-03-27 10:46 UTC, MAhmadShah commented
Just one comment other wise LGTM!

2024-03-27 14:31 UTC, MAhmadShah approved these changes

2024-03-28 10:50 UTC, jimoleary requested changes
The ```no_format``` variable name looks a bit odd, can we change it to ```lint_format```?

This hurts my head less.

I assume you went do this path so as not to override the builtin ```format``` function.

2024-03-28 10:50 UTC, jimoleary commented on docs/using.md
> +	./run-genny lint-yaml  --no-format # Lint all YAML files
Do we need ```--no-format``` here if the default is false?

2024-03-28 10:50 UTC, jimoleary commented on src/lamplib/src/genny/tasks/yaml_linter.py
> +        yamllint.cli.run(yamllint_argv)
How are errors handled here? What do we do if ```yamllint.cli.run(yamllint_argv)``` fails?

2024-03-28 14:52 UTC, jimoleary commented on docs/using.md
> +	./run-genny lint-yaml  --no-format # Lint all YAML files
oh yeah, let's make that the default for now.

2024-03-28 14:52 UTC, jimoleary commented on src/lamplib/src/genny/cli.py
> +def lint_yaml(ctx: click.Context, no_format: bool):
lint_format defaulting to False or no_format to True would be the sensible state .

2024-03-28 17:10 UTC, jimoleary approved these changes
LGTM

I think we are probably on the hook for MongosyncScripts.yml, if I find out anything different after this merges ... I'll change it.

2024-03-29 00:33 UTC, merged