DEVPROD-6041 Documentation generation improvements.
mongodb/genny pull request #1182
Opened 2024-04-03 19:29 UTC by ahartschen

Thanks for submitting a PR to the Genny repo. Please include the following fields (if relevant) prior to submitting your PR.

**Jira Ticket:** DEVPROD-6041

**Whats Changed:**  
1. Made separate documentation files for workloads and phases.
2. Added hyperlinks to the respective workload and phase yamls in the docs.

2024-04-03 20:17 UTC, dalyd approved these changes
The change LGTM. I have two requests that can be in this PR or separate. 
1. Can we add a horizontal line between entries? 
2. Can we link to the generated docs from https://github.com/mongodb/genny/blob/3765880c20407c696af4c56568fa932b4940c342/docs/start.md?

2024-04-03 20:17 UTC, dalyd commented on src/lamplib/src/genny/templates/documentation.md.j2
>  {% for workload in workloads %}
Can we add a line break inside this loop, either at the top or bottom? I think 
```
---
```
Would be sufficient.

2024-04-04 09:51 UTC, SimonEismann requested changes

2024-04-04 09:51 UTC, SimonEismann commented on src/lamplib/src/genny/templates/documentation.md.j2
> +# Workload Documentation
The added space here makes me think that we aren't linting this. That's probably okay in the commit queue, but running some linter over this locally might be a good idea.

2024-04-04 09:51 UTC, SimonEismann commented on docs/generated/workloads.md
> +# Workload Documentation
We need some introductory text here:
* What workloads does this cover?
* What information is available for each workload?
* Where does this documentation come from?
* What to do if documentation is missing/bad?
* ...

2024-04-04 09:51 UTC, SimonEismann commented on docs/generated/workloads.md
This is a bit ambitious, so feel free to ignore.

We could have two sections here:
* Active Workloads (workloads with an autorun section that run on sys-perf)
* Other Workloads (the rest)

My concern is that users might find a workload on this page and then go looking for it in sys-perf and not find it.

2024-04-04 17:27 UTC, dalyd commented on src/lamplib/src/genny/templates/documentation.md.j2
>  {% for workload in workloads %}
Ah, yeah -- the heading including the line does make that confusing.

2024-04-05 08:59 UTC, SimonEismann approved these changes

2024-04-05 09:03 UTC, SimonEismann commented on docs/generated/workloads.md
Done: https://jira.mongodb.org/browse/DEVPROD-6160

2024-04-15 17:49 UTC, merged