TIG-2819 Update toolchain download URLs to point to new S3 bucket
mongodb/genny pull request #486
Opened 2021-06-04 19:22 UTC by vrachev

See https://github.com/10gen/vcpkg/pull/11 for more details. This makes genny download the toolchain from S3. Because the git rev is not constant amongst all the binaries, I added a workaround where we touch a file in the gennytoolchain repo with the githash as the name and check that it's the same githash as is requested. (The git hash is the hash of the final vcpkg change, but the macos gennytoolchain artifact was created before the commit was merged, and therefore its git hash is different).

2021-06-04 19:27 UTC, vrachev commented
Tested this locally on macos as well as a ubuntu1804 workstation

2021-06-08 18:47 UTC, aggrand requested changes
Great job getting this to work and deciphering all the vcpkg stuff!

Just a question about the aws bucket mechanism. Was the problem that macos is flaky but still works sometimes? If so, would be able to just re-execute the task until we get a green macos build, then leave it be? That way we could keep downloading from the task; I feel like if we want to use AWS buckets we'd want to have a dedicated "push" task like curator does. Manual aws bucketing seems a bit inscrutable. Also continuing to download from the task would mean it seamlessly starts working again after we update the toolchain.

2021-06-08 18:47 UTC, aggrand commented on src/lamplib/src/genny/toolchain.py
> +        if os.path.exists(self.toolchain_git_hash_file):
Won't this only check whether there is a git hash file in the first place, without checking that it's the right hash?

2021-06-09 15:40 UTC, vrachev commented
@aggrand Yeah I think we can try just committing to the waterfall until we get a green build. Mind taking a look at https://github.com/10gen/vcpkg/pull/11 for that?

2021-06-10 13:45 UTC, vrachev commented
No longer needed with #488

2021-06-10 13:45 UTC, closed without merging