PERF-2572 add warmup phase, lower initial/ secondary document count and name each index.
mongodb/genny pull request #578
Opened 2021-11-18 11:56 UTC by jimoleary

There is a [patch](https://spruce.mongodb.com/version/61963c6a1e2d176241fc9742/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC), but it is being blocked by a compile error.

2021-11-18 18:35 UTC, apodelko submitted a review, later dismissed
LGTM, although I won't be surprised if it won't eliminate variability completely. But we probably need this step anyway even if we need to investigate it further.

2021-11-18 18:38 UTC, apodelko commented
Another option may be to run the patch multiple times and see how much the fix helps.

2021-11-18 21:11 UTC, dalyd requested changes

2021-11-18 21:11 UTC, dalyd commented on src/workloads/transactions/LLTMixed.yml
>  GlobalDefaults:
By my reading this is: 
0. Queisce
1. Initial Load
2. Warmup
3. Second Load

Then repeating: quiesce, warmup, test. Is that correct? 
If it is I can't find the phase 5 warmup. 

Could we document this flow?

2021-12-01 17:22 UTC, jimoleary commented
Updated the branch with PR comments. Started a new [patch](https://spruce.mongodb.com/version/61a7acd6850e610a956b7ffa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

*note:* I'm actually going to move the current LLTMixed.yml to LLTMixedWarmup.yml  and reinstate the old version before committing. This is for 2 reasons:
1. We want to keep the original workload, so keeping the task name keeps the history. This test will likely be noisy but it does provide a useful signal.
2. I wanted to be able to compare the new workload to the old one.

2021-12-01 22:25 UTC, dalyd commented on src/workloads/transactions/LLTMixed.yml
>  GlobalDefaults:
Done below.

2021-12-01 22:27 UTC, dalyd approved these changes
Alright, my issues have been addressed. I'll leave it with the two of you to make sure it actually works and runs :)

2025-05-02 05:33 UTC, closed without merging