TIG-3323 Add documentation for workloads owned by service arch
mongodb/genny pull request #712
Opened 2022-07-13 15:36 UTC by jasonjhchan

2022-07-14 20:43 UTC, aggrand approved these changes
LGTM w.r.t. using genny syntax correctly but I can't comment on the workloads or usefulness of the descriptions for the relevant stakeholders, someone on service arch or maybe @allenwux would have better comments on it

2022-07-15 17:48 UTC, BlakeIsBlake requested changes

2022-07-15 17:48 UTC, BlakeIsBlake commented on src/workloads/networking/SecondaryAllowed.yml
> +  are 100 threads allocated to run this operation, with a rate limit of 1 thread acting per 1ms.
/s/this operation/the find operations

2022-07-15 17:48 UTC, BlakeIsBlake commented on src/workloads/networking/ServiceArchitectureWorkloads.yml
> +  are 100 threads allocated to run this operation, with a rate limit of 1 thread acting per 1ms.
/s/this operation/the find operations

2022-07-15 17:48 UTC, BlakeIsBlake commented on src/workloads/networking/SecondaryAllowed.yml
> +  are 100 threads allocated to run this operation, with a rate limit of 1 thread acting per 1ms.
1 microsecond, not millisecond

2022-07-15 17:48 UTC, BlakeIsBlake commented on src/workloads/networking/ServiceArchitectureWorkloads.yml
> +  are 100 threads allocated to run this operation, with a rate limit of 1 thread acting per 1ms.
1 microsecond not millisecond

2022-07-15 17:56 UTC, jasonjhchan reviewed
addressed comments

2022-07-15 17:56 UTC, jasonjhchan commented on src/workloads/networking/SecondaryAllowed.yml
> +  are 100 threads allocated to run this operation, with a rate limit of 1 thread acting per 1ms.
whoops nice catch

2022-07-15 17:56 UTC, jasonjhchan commented on src/workloads/networking/ServiceArchitectureWorkloads.yml
> +  are 100 threads allocated to run this operation, with a rate limit of 1 thread acting per 1ms.
done

2022-07-15 17:57 UTC, BlakeIsBlake approved these changes

2022-07-15 18:00 UTC, jasonjhchan commented
evergreen merge

2022-07-15 18:24 UTC, merged