PERF-4052 Allow sampling Bonsai variants to run auto Genny workloads
mongodb/genny pull request #878
Opened 2023-05-02 11:17 UTC by RuoxinXu

Thanks for submitting a PR to the Genny repo. Please include the following fields (if relevant) prior to submitting your PR.

**Jira Ticket:** PERF-4053

**Whats Changed:**  
Adding DSI setup for sampling Bonsai variant

**Patch testing results:**  
https://spruce.mongodb.com/version/644fdccb0305b943b8f32f3e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

**Related PRs:**   
https://github.com/10gen/dsi/pull/1271

2023-05-02 12:56 UTC, alyacb requested changes
Thanks Roy! I think we should also try to include these files for the standalone-sbe variant:
- src/workloads/query/PercentilesAgg.yml
- src/workloads/query/PercentilesExpr.yml
- src/workloads/query/PercentilesWindow.yml
- src/workloads/query/PercentilesWindowSpillToDisk.yml

We should also include the genny workloads for replicaset variants. A quick grep for `single-replica-sbe` shows these files need the `single-replica-sampling-bonsai` variant as well:
- src/workloads/query/ConstantFoldArithmetic.yml
- src/workloads/query/GraphLookupWithOnlyUnshardedColls.yml
- src/workloads/query/LookupWithOnlyUnshardedColls.yml
- src/workloads/scale/LargeIndexedIns.yml:69
- src/workloads/scale/MajorityReads10KThreads.yml
- src/workloads/scale/MixedWorkloadsGenny.yml
- src/workloads/scale/MixedWorkloadsGennyRateLimited.yml
- src/workloads/scale/ScanWithLongLived.yml
- src/workloads/transactions/LLTMixed.yml

If any of these workloads fail/ if BigUpdate continues to fail on the patch, we could just comment out the new variant, create a ticket, and leave a TODO to enable it later.

2023-05-09 15:46 UTC, alyacb approved these changes
LGTM! Thanks, Roy! 🎉

2023-05-09 17:06 UTC, lriuui0x0 approved these changes

2023-05-09 17:06 UTC, lriuui0x0 approved these changes

2023-05-10 13:08 UTC, RuoxinXu commented
evergreen merge

2023-05-10 14:30 UTC, merged