PERF-4147 - New workload to help report CPU cycle metrics
mongodb/genny pull request #922
Opened 2023-06-07 15:38 UTC by MAhmadShah

**Jira Ticket:** [PERF-4147](https://jira.mongodb.org/browse/PERF-4147)

**Whats Changed:**  
We have added the CPYCycleMetrics workload that will help us report on cpu cycle metrics on the new Linux 3-Node ReplSet CPU Cycle Metrics 2023-06 variant.

**Patch testing results:**  
[Patch](https://spruce.mongodb.com/version/6480d13632f417f2ff943558/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) showing the results of the new workload running on the new variant. Looking at the trend charts view, we can see the new metrics being reported.

**Related PRs:**   

- https://github.com/10gen/mongo/pull/13421
- https://github.com/10gen/dsi/pull/1309

2023-06-09 09:07 UTC, SimonEismann reviewed
Some feedback around the new tests

2023-06-09 12:35 UTC, MAhmadShah commented on src/workloads/query/CPUCycleMetrics.yml
> +  a: {^RandomInt: {min: 0, max: *NumDocs}}
Good call, I've updated this to increment instead

2023-06-09 12:36 UTC, MAhmadShah commented on src/workloads/query/CPUCycleMetrics.yml
> +      maxPoolSize: 1000
Not necessary, was put as a place holder and forgot to remove it. Gone now.

2023-06-09 12:37 UTC, MAhmadShah commented on src/workloads/query/CPUCycleMetrics.yml
> +          RecordFailure: true
Yes good call, I've updated ThrowOnFailure to be true

2023-06-09 12:37 UTC, MAhmadShah commented on src/workloads/query/CPUCycleMetrics.yml
> +ActorTemplates:
Done

2023-06-09 12:39 UTC, MAhmadShah commented on src/workloads/query/CPUCycleMetricsMixed.yml
> +SchemaVersion: 2018-07-01
My goal was to setup a workload where we can perform CRUD actions. So here the idea was to insert one document, update it to a new value and then delete it. We repeat this 10k times and watch the CPU cycle metrics.

2023-06-12 12:30 UTC, SimonEismann requested changes
As discussed via slack, let's split the second test into two to three separate tests.

2023-06-12 14:36 UTC, SimonEismann requested changes
Minor nits

2023-06-12 14:36 UTC, SimonEismann commented on src/workloads/query/CPUCycleMetrics.yml
CPUCycleMetric.yml -> CPUCycleMetricFind.yml?

2023-06-12 14:36 UTC, SimonEismann commented on src/workloads/query/CPUCycleMetricsDelete.yml
> +  - Name: UpdateActor
UpdateActor --> DeleteActor

2023-06-12 14:36 UTC, SimonEismann commented on src/workloads/query/CPUCycleMetricsUpdate.yml
> +                Update: { $set: { ^RandomInt: { min: 0, max: *NumDocs } } }
We might want to update b instead of a.

Also, do we want to use inc to filter for an item?

2023-06-12 18:11 UTC, MAhmadShah commented
@SimonEismann updated patch showing all new workloads can be found here: https://spruce.mongodb.com/version/648734461e2d17497dae0861/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

2023-06-13 08:23 UTC, SimonEismann approved these changes
LGTM! Kinda cool to see that for the find workload, the secondaries have a much better CPI since they aren't doing any replication work.

2023-06-13 14:09 UTC, merged