EVG-20571: Create a mechanism to redact secrets from all strings in log entries that Genny creates via structlog
mongodb/genny pull request #991
Opened 2023-08-16 09:17 UTC by PyGeek03

**Jira Ticket:** EVG-20571

**Whats Changed:**  
Create a mechanism to redact secrets from all strings in log entries that Genny creates via structlog. This is done via a custom structlog-compatible processor called `SecretsRedactor`. For now this processor only redacts passwords in URLs, but more secrets could be added to its member attribute `regex_to_redaction`, which is a dictionary mapping a secret's regex pattern to the corresponding redaction string to replace the secret with.

Exceptions and tracebacks raised by Genny's Python code are now logged by structlog to enable this.

This PR does not guarantee that secrets in log entries, exceptions and tracebacks created by Genny dependencies and Genny's C++ code are redacted, only those created directly by Genny's Python code.

**Patch testing results:**  
If applicable, link a patch test showing code changes running successfully

2023-10-10 05:54 UTC, lgfang approved these changes

2023-10-17 06:46 UTC, PyGeek03 commented on src/lamplib/src/genny/loggers.py
> +    re.compile(r"mongo(.+?)-p ([^;' ]*)"): r"mongo\g<1>-p [REDACTED]",  # -p flag of mongo
I don't like regex either, but this PR is basically a copy of the corresponding DSI PR, and the issue we are dealing with in DSI is quite annoying: The log lines from clients are sent to DSI as plain text, and I can't find any way to filter plain text other than using regex.

2023-11-16 04:43 UTC, thessem requested changes
My review there essentially has the same content as https://github.com/10gen/dsi/pull/1377#pullrequestreview-1733487017. I think this is a well described PR and you've implemented your method well, but I am not convinced on the method.

2023-11-16 04:43 UTC, thessem commented on src/lamplib/src/genny/cli.py
> +@slog_exception
Is it possible to do this more elegantly than more decorators?

2024-04-18 01:24 UTC, closed without merging